name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          scripts/install_light.sh
          pip install -r knowledgeplus_design-main/requirements-tests.txt
      - name: Run tests
        run: pytest -q
