---
name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
            ${{ hashFiles('knowledgeplus_design-main/requirements-light.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r knowledgeplus_design-main/requirements-light.txt
          pip install -r knowledgeplus_design-main/requirements-tests.txt
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --files $(git ls-files '*.py')

      - name: Run tests
        run: pytest -q
